name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Install dependencies
        # Before merging to main, re-run the install for security purposes
        # https://yarnpkg.com/features/zero-installs/#does-it-have-security-implications
        # run: yarn install --check-cache
        run: yarn install
      - name: Build
        run: yarn ci:build
      - name: Test
        run: yarn ci:test
      - name: Create release pull request
        uses: changesets/action@master
        with:
          version: yarn changeset version
      - name: Publish
        run: yarn ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.FORESTRYIO_NPM_AUTH_TOKEN }}
          FORESTRYIO_NPM_AUTH_IDENT: ${{ secrets.FORESTRYIO_NPM_AUTH_IDENT }}
          FORESTRYIO_NPM_AUTH_TOKEN: ${{ secrets.FORESTRYIO_NPM_AUTH_TOKEN }}
